'use strict';
const byId=id=>document.getElementById(id);let active=0;let answers={};
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
byId('scope').textContent=EDITION.demo?'10ケース版の無料見本：3ケース':'デジタル商品の対応練習：10ケース';
byId('rights').textContent='購入者・取得者と同じ組織内の学習に利用できます。教材そのものの再配布・転売・公開アップロードは含みません。';
if(EDITION.buyURL){byId('offer').hidden=false;byId('buy').href=EDITION.buyURL;}
function progress(){const completed=Object.keys(answers).length;byId('progress').textContent=`${completed}/${TRAINING_CASES.length}ケースを確認。正答 ${Object.entries(answers).filter(([k,v])=>TRAINING_CASES.find(c=>c.id===k)?.correct===v).length}件。`;}
function render(){const c=TRAINING_CASES[active];byId('case-list').replaceChildren();TRAINING_CASES.forEach((item,i)=>{const b=el('button',item.id+' '+item.title);b.type='button';b.setAttribute('aria-current',String(i===active));b.onclick=()=>{active=i;stateRevision++;render();};byId('case-list').append(b);});const root=byId('case');root.replaceChildren(el('h2',c.id+' '+c.title),el('h3','購入者からの相談'),el('blockquote',c.ask),el('h3','このケースで分かっていること'));const ul=el('ul');c.facts.forEach(f=>ul.append(el('li',f)));root.append(ul,el('h3','この架空店舗の対応方針'));c.rules.forEach(r=>{const p=el('p',undefined,'rule');p.append(el('code',r.id+' '),el('span',r.text));root.append(p);});const form=el('form');const fs=el('fieldset');fs.append(el('legend','次に担当者が行うことは？'));c.options.forEach((o,i)=>{const l=el('label',undefined,'choice');const input=el('input');input.type='radio';input.name='answer';input.value=String(i);input.required=true;input.checked=answers[c.id]===i;l.append(input,el('span',o));fs.append(l);});const submit=el('button','根拠と引継ぎ例を確認');submit.type='submit';form.append(fs,submit);const feedback=el('section');feedback.id='feedback';feedback.setAttribute('aria-live','polite');form.onsubmit=e=>{e.preventDefault();const checked=form.querySelector('input:checked');if(!checked)return;answers[c.id]=Number(checked.value);stateRevision++;showFeedback(feedback,c);progress();};root.append(form,feedback);if(answers[c.id]!==undefined)showFeedback(feedback,c);progress();}
function showFeedback(root,c){root.replaceChildren(el('h3',answers[c.id]===c.correct?'このケースの根拠と一致':'確認した事実と約束を分け直しましょう'),el('p','このケースの選択：'+c.options[c.correct]),el('p',c.why),el('h3','担当者への引継ぎ例'),el('p',c.handoff,'handoff'));const refs=el('p','根拠：'+c.rules.map(r=>r.id).join('、'),'small');root.append(refs);}
function exportText(){if(!Object.keys(answers).length){byId('notice').textContent='まず一つのケースを確認してください。';return;}const lines=['返信の判断をそろえる／架空ケースの振り返り','これは実顧客の対応・資格・返金可否の判断ではありません。',''];TRAINING_CASES.forEach(c=>{lines.push(c.id+' '+c.title,answers[c.id]===undefined?'未回答':'選んだ答え：'+c.options[answers[c.id]],'このケースの根拠：'+c.rules.map(r=>r.id+' '+r.text).join(' ／ '),'引継ぎ例：'+c.handoff,'');});const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=el('a');a.href=url;a.download='reply-training-review.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);byId('notice').textContent='振り返りファイルを作成しました。ブラウザのダウンロード先を確認してください。';}
// Manual progress files contain choices and position, never scores or case text.
const PROGRESS_LANG = 'ja';
let stateRevision=0;
function caseFingerprint(cases){
 const k=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
 const bytes=new TextEncoder().encode(JSON.stringify(cases)),padded=new Uint8Array(Math.ceil((bytes.length+9)/64)*64);padded.set(bytes);padded[bytes.length]=128;const dv=new DataView(padded.buffer);dv.setUint32(padded.length-4,bytes.length*8,false);const h=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19];const rr=(x,n)=>(x>>>n)|(x<<(32-n));
 for(let offset=0;offset<padded.length;offset+=64){const w=new Uint32Array(64);for(let i=0;i<16;i++)w[i]=dv.getUint32(offset+i*4,false);for(let i=16;i<64;i++){const a=w[i-15],b=w[i-2];w[i]=(w[i-16]+(rr(a,7)^rr(a,18)^(a>>>3))+w[i-7]+(rr(b,17)^rr(b,19)^(b>>>10)))>>>0;}let [a,b,c,d,e,f,g,v]=h;for(let i=0;i<64;i++){const t1=(v+(rr(e,6)^rr(e,11)^rr(e,25))+((e&f)^(~e&g))+k[i]+w[i])>>>0,t2=((rr(a,2)^rr(a,13)^rr(a,22))+((a&b)^(a&c)^(b&c)))>>>0;v=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0;}[a,b,c,d,e,f,g,v].forEach((x,i)=>h[i]=(h[i]+x)>>>0);}
 return 'sha256:'+h.map(x=>x.toString(16).padStart(8,'0')).join('');
}
function progressRecord(){return {format:'support-decision-progress',version:1,lang:PROGRESS_LANG,edition:EDITION.demo?'free3':'paid10',fingerprint:caseFingerprint(TRAINING_CASES),active,answers:{...answers}};}
function readProgress(text){
 const msg=PROGRESS_LANG==='ja'?'この教材・言語・ケース内容に対応する進行JSON（32KBまで）が必要です。':'Use a progress JSON for this exact workbook, language and case content (up to 32KB).';
 if(typeof text!=='string'||new TextEncoder().encode(text).length>32768)throw Error(msg);
 let x;try{x=JSON.parse(text);}catch{throw Error(msg);}
 const keys=['format','version','lang','edition','fingerprint','active','answers'];
 if(!x||typeof x!=='object'||Array.isArray(x)||Object.keys(x).length!==keys.length||Object.keys(x).some(k=>!keys.includes(k))||x.format!=='support-decision-progress'||x.version!==1||x.lang!==PROGRESS_LANG||x.edition!==(EDITION.demo?'free3':'paid10')||x.fingerprint!==caseFingerprint(TRAINING_CASES)||!Number.isInteger(x.active)||x.active<0||x.active>=TRAINING_CASES.length||!x.answers||typeof x.answers!=='object'||Array.isArray(x.answers))throw Error(msg);
 const next={};for(const [id,value]of Object.entries(x.answers)){const c=TRAINING_CASES.find(c=>c.id===id);if(!c||!Number.isInteger(value)||value<0||value>=c.options.length)throw Error(msg);next[id]=value;}
 return {active:x.active,answers:next};
}
function saveProgress(){const text=JSON.stringify(progressRecord(),null,2)+'\n';const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=el('a');a.href=url;a.download='support-decision-'+PROGRESS_LANG+'-'+(EDITION.demo?'free3':'paid10')+'-progress.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);byId('notice').textContent=PROGRESS_LANG==='ja'?'回答と現在位置のJSONを保存しました。次回、同じ教材・言語で読み込めます。':'Saved your answers and current case as JSON. Reload it in the same workbook and language.';}
byId('save-progress').onclick=saveProgress;
byId('load-progress').onchange=async()=>{const input=byId('load-progress'),file=input.files[0],revision=stateRevision;if(!file)return;try{if(file.size>32768)throw Error(PROGRESS_LANG==='ja'?'進行JSONは32KBまでです。':'Progress JSON must be at most 32KB.');const next=readProgress(await file.text());if(revision!==stateRevision)throw Error(PROGRESS_LANG==='ja'?'読込中に練習が進みました。もう一度ファイルを選んでください。':'Practice changed while loading. Choose the file again.');active=next.active;answers=next.answers;stateRevision++;render();byId('notice').textContent=PROGRESS_LANG==='ja'?'回答と現在位置を復元しました。正答数は今のケース内容から再計算しました。':'Restored answers and current case. The score was recalculated from the current cases.';}catch(error){byId('notice').textContent=(PROGRESS_LANG==='ja'?'読み込めませんでした。現在の回答と位置は保持しています。 ':'Could not load. Your current answers and position are preserved. ')+error.message;}finally{input.value='';}};

byId('export').onclick=exportText;byId('reset').onclick=()=>{answers={};active=0;stateRevision++;render();byId('notice').textContent='練習の進行を初期化しました。保存済みファイルは削除しません。';};render();
