'use strict';
const byId=id=>document.getElementById(id);let active=0;let answers={};
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
byId('scope').textContent=EDITION.demo?'10ケース版の無料見本：3ケース':'デジタル商品の対応練習：10ケース';
byId('rights').textContent='購入者・取得者と同じ組織内の学習に利用できます。教材そのものの再配布・転売・公開アップロードは含みません。';
if(EDITION.buyURL){byId('offer').hidden=false;byId('buy').href=EDITION.buyURL;}
function progress(){const completed=Object.keys(answers).length;byId('progress').textContent=`${completed}/${TRAINING_CASES.length}ケースを確認。正答 ${Object.entries(answers).filter(([k,v])=>TRAINING_CASES.find(c=>c.id===k)?.correct===v).length}件。`;}
function render(){const c=TRAINING_CASES[active];byId('case-list').replaceChildren();TRAINING_CASES.forEach((item,i)=>{const b=el('button',item.id+' '+item.title);b.type='button';b.setAttribute('aria-current',String(i===active));b.onclick=()=>{active=i;render();};byId('case-list').append(b);});const root=byId('case');root.replaceChildren(el('h2',c.id+' '+c.title),el('h3','購入者からの相談'),el('blockquote',c.ask),el('h3','このケースで分かっていること'));const ul=el('ul');c.facts.forEach(f=>ul.append(el('li',f)));root.append(ul,el('h3','この架空店舗の対応方針'));c.rules.forEach(r=>{const p=el('p',undefined,'rule');p.append(el('code',r.id+' '),el('span',r.text));root.append(p);});const form=el('form');const fs=el('fieldset');fs.append(el('legend','次に担当者が行うことは？'));c.options.forEach((o,i)=>{const l=el('label',undefined,'choice');const input=el('input');input.type='radio';input.name='answer';input.value=String(i);input.required=true;input.checked=answers[c.id]===i;l.append(input,el('span',o));fs.append(l);});const submit=el('button','根拠と引継ぎ例を確認');submit.type='submit';form.append(fs,submit);const feedback=el('section');feedback.id='feedback';feedback.setAttribute('aria-live','polite');form.onsubmit=e=>{e.preventDefault();const checked=form.querySelector('input:checked');if(!checked)return;answers[c.id]=Number(checked.value);showFeedback(feedback,c);progress();};root.append(form,feedback);if(answers[c.id]!==undefined)showFeedback(feedback,c);progress();}
function showFeedback(root,c){root.replaceChildren(el('h3',answers[c.id]===c.correct?'このケースの根拠と一致':'確認した事実と約束を分け直しましょう'),el('p','このケースの選択：'+c.options[c.correct]),el('p',c.why),el('h3','担当者への引継ぎ例'),el('p',c.handoff,'handoff'));const refs=el('p','根拠：'+c.rules.map(r=>r.id).join('、'),'small');root.append(refs);}
function exportText(){if(!Object.keys(answers).length){byId('notice').textContent='まず一つのケースを確認してください。';return;}const lines=['返信の判断をそろえる／架空ケースの振り返り','これは実顧客の対応・資格・返金可否の判断ではありません。',''];TRAINING_CASES.forEach(c=>{lines.push(c.id+' '+c.title,answers[c.id]===undefined?'未回答':'選んだ答え：'+c.options[answers[c.id]],'このケースの根拠：'+c.rules.map(r=>r.id+' '+r.text).join(' ／ '),'引継ぎ例：'+c.handoff,'');});const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=el('a');a.href=url;a.download='reply-training-review.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);byId('notice').textContent='振り返りファイルを作成しました。ブラウザのダウンロード先を確認してください。';}
byId('export').onclick=exportText;byId('reset').onclick=()=>{answers={};active=0;render();byId('notice').textContent='練習の進行を初期化しました。保存済みファイルは削除しません。';};render();
