'use strict';
const $=id=>document.getElementById(id);
function saveText(name,text,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
const keys=['title','ask','facts','rule','opt0','opt1','opt2','correct','why','handoff'];let current=null,generation=0;
function clearCurrent(){current=null;$('result').hidden=true;$('options').replaceChildren();for(const id of ['case-title','ask-view','facts-view','rule-view','feedback'])$(id).textContent='';$('download').disabled=true;$('download-html').disabled=true;}
function raw(){return Object.fromEntries(keys.map(k=>[k,$(k).value]));}
function prepareCase(data){return readCaseJSON(JSON.stringify(checkCase(data),null,2)+'\n');}
function fromRaw(d){return prepareCase({title:d.title,ask:d.ask,facts:d.facts.split('\n').filter(x=>x.trim()),rule:d.rule,options:[d.opt0,d.opt1,d.opt2],correct:Number(d.correct),why:d.why,handoff:d.handoff});}
function draw(c){current=c;$('case-title').textContent=c.title;$('ask-view').textContent=c.ask;$('facts-view').textContent=c.facts.join('\n');$('rule-view').textContent=c.rule;$('feedback').textContent='';$('options').replaceChildren();c.options.forEach((text,i)=>{const b=document.createElement('button');b.type='button';b.textContent=(i+1)+' '+text;b.onclick=()=>{$('feedback').textContent=(i===c.correct?'作者が設定した正解':'作者が設定した正解は別の案')+'\n理由: '+c.why+'\n引継ぎ: '+c.handoff;};$('options').append(b);});$('result').hidden=false;$('download').disabled=false;$('download-html').disabled=false;}
function fill(c){for(const k of ['title','ask','why','handoff'])$(k).value=c[k];$('facts').value=c.facts.join('\n');$('rule').value=c.rule;c.options.forEach((v,i)=>$('opt'+i).value=v);$('correct').value=String(c.correct);}
$('example').onclick=()=>{generation++;clearCurrent();fill({title:'架空のリンク確認',ask:'リンクが開けません',facts:['支払い完了は確認済み','ブラウザとエラーは未確認'],rule:'未確認の解決や再送を完了と報告しない',options:['環境と公開状態を確認する','再送済みと断言する','パスワードを聞く'],correct:0,why:'支払いは閲覧成功や再送完了の証明ではない',handoff:'対応担当が環境・公開・エラーを確認'});$('status').textContent='架空例を入力しました。練習として試すと保存できます。';};
$('form').oninput=()=>{generation++;clearCurrent();$('status').textContent='入力が変わりました。練習を作り直してから保存してください。';};
$('form').onsubmit=e=>{e.preventDefault();generation++;try{const next=fromRaw(raw());draw(next);$('status').textContent='入力した一問を作成しました。正解と理由は作者が決めたものです。';}catch(error){clearCurrent();$('status').textContent='入力を確認してください。 '+error.message;}};
$('load').onchange=async()=>{const file=$('load').files[0];if(!file)return;const token=++generation;try{if(file.size>32768)throw Error('ケースJSONは32KBまでです');const next=prepareCase(readCaseJSON(await file.text()));if(token!==generation)return;fill(next);draw(next);$('status').textContent='ケースを読み込みました。内容を確認して練習できます。';}catch(error){if(token!==generation)return;$('status').textContent='読み込めませんでした。現在の入力と練習は保持しています。 '+error.message;}finally{$('load').value='';}};
$('download').onclick=()=>{if(!current)return;saveText('my-fictional-training-case.json',JSON.stringify(current,null,2)+'\n','application/json');$('status').textContent='編集用のケースJSONを保存しました。';};
$('download-html').onclick=()=>{if(!current)return;try{const html=CasePlayerHTML.buildCaseHTML(current,checkCase);saveText('my-fictional-training-case.html',html,'text/html;charset=utf-8');$('status').textContent='自作の一問HTMLを保存しました。JavaScriptとローカルHTMLに対応するブラウザで、単体で開いて練習できます。';}catch(error){$('status').textContent='HTMLを保存できませんでした。 '+error.message;}};
clearCurrent();
