(function(root){
'use strict';
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function buildCaseHTML(data,validator){
 const c=validator(data),json=JSON.stringify(c).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
 return '<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'unsafe-inline\'; style-src \'unsafe-inline\'; connect-src \'none\'; img-src \'none\'; base-uri \'none\'; form-action \'none\'"><title>'+escapeHTML(c.title)+'｜自作の対応練習</title><style>*{box-sizing:border-box}body{margin:0;background:#f4f2eb;color:#19373a;font:17px/1.8 system-ui,sans-serif}main{max-width:820px;margin:auto;padding:30px 22px 65px}h1{font-size:clamp(27px,5vw,42px);line-height:1.3;overflow-wrap:anywhere}h2{font-size:22px}section{background:#fffdf8;border:1px solid #c9d7d5;border-radius:16px;padding:22px;margin:22px 0}blockquote{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}p,li{white-space:pre-wrap;overflow-wrap:anywhere}button{font:inherit;display:block;background:#075d62;color:white;padding:12px 18px;border:0;border-radius:8px;cursor:pointer;margin:12px 0;width:100%;text-align:left;overflow-wrap:anywhere}button[aria-pressed=true]{outline:3px solid #da980e;outline-offset:3px}.small{font-size:14px;color:#526c70}#reset{background:#e4eeeb;color:#19373a;width:auto}:focus-visible{outline:3px solid #da980e;outline-offset:3px}[hidden]{display:none!important}@media(max-width:430px){main{padding:22px 15px 45px}section{padding:18px}}</style></head><body><main><p class="small">作者が用意した架空の一問</p><h1 id="title"></h1><p>確認した事実と、これから決めることを分けて、次の作業を選びます。</p><section><h2>相談</h2><blockquote id="ask"></blockquote><h2>このケースの事実</h2><ul id="facts"></ul><h2>この練習の規則</h2><p id="rule"></p></section><section><h2>次に行うことは？</h2><div id="choices"></div><div id="feedback" hidden aria-live="polite"><h2 id="result"></h2><p id="why"></p><h2>引継ぎ例</h2><p id="handoff"></p></div><button id="reset" type="button">もう一度選ぶ</button></section><p class="small">正解と根拠は作者が設定したものです。実顧客の対応・返金・法的な可否を認定しません。入力の送信・自動保存はありません。JavaScriptを使えるローカルHTML対応ブラウザで開いてください。</p><p class="small">教材コードは取得者と同じ組織内の学習・研修に利用できます。教材コードの再配布・転売・公開アップロードは含みません。AIを用いて制作したコードを使用しています。</p></main><script id="case-data" type="application/json">'+json+'</script><script>\n'+
 `"use strict";
 const c=JSON.parse(document.getElementById('case-data').textContent),get=id=>document.getElementById(id);
 for(const k of ['title','ask','rule'])get(k).textContent=c[k];
 for(const fact of c.facts){const li=document.createElement('li');li.textContent=fact;get('facts').append(li);}
 const buttons=[];c.options.forEach((option,index)=>{const b=document.createElement('button');b.type='button';b.textContent=(index+1)+' '+option;b.setAttribute('aria-pressed','false');b.onclick=()=>{for(const other of buttons)other.setAttribute('aria-pressed',String(other===b));get('result').textContent=index===c.correct?'作者が設定した正解':'作者が設定した正解は別の案';get('why').textContent='理由：'+c.why;get('handoff').textContent=c.handoff;get('feedback').hidden=false;};buttons.push(b);get('choices').append(b);});
 get('reset').onclick=()=>{for(const b of buttons)b.setAttribute('aria-pressed','false');get('feedback').hidden=true;get('result').textContent='';get('why').textContent='';get('handoff').textContent='';};
 `+'</script></body></html>';
}
const api={buildCaseHTML};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.CasePlayerHTML=api;
})(typeof window==='undefined'?globalThis:window);
