'use strict';
const byId=id=>document.getElementById(id);let active=0;let answers={};
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
byId('scope').textContent=EDITION.demo?'Three complete free cases from the 10-case workbook':'10 fictional support decision cases';
byId('rights').textContent='For learning within the purchaser/recipient organization. No redistribution, resale or public uploads of the workbook.';
if(EDITION.buyURL){byId('offer').hidden=false;byId('buy').href=EDITION.buyURL;}
function progress(){const completed=Object.keys(answers).length;byId('progress').textContent=`${completed}/${TRAINING_CASES.length} cases reviewed. Correct in this fictional exercise: ${Object.entries(answers).filter(([k,v])=>TRAINING_CASES.find(c=>c.id===k)?.correct===v).length}.`;}
function render(){const c=TRAINING_CASES[active];byId('case-list').replaceChildren();TRAINING_CASES.forEach((item,i)=>{const b=el('button',item.id+' '+item.title);b.type='button';b.setAttribute('aria-current',String(i===active));b.onclick=()=>{active=i;render();};byId('case-list').append(b);});const root=byId('case');root.replaceChildren(el('h2',c.id+' '+c.title),el('h3','The buyer asks'),el('blockquote',c.ask),el('h3','Known facts in this case'));const ul=el('ul');c.facts.forEach(f=>ul.append(el('li',f)));root.append(ul,el('h3','This fictional shop policy'));c.rules.forEach(r=>{const p=el('p',undefined,'rule');p.append(el('code',r.id+' '),el('span',r.text));root.append(p);});const form=el('form');const fs=el('fieldset');fs.append(el('legend','What should the agent do next?'));c.options.forEach((o,i)=>{const l=el('label',undefined,'choice');const input=el('input');input.type='radio';input.name='answer';input.value=String(i);input.required=true;input.checked=answers[c.id]===i;l.append(input,el('span',o));fs.append(l);});const submit=el('button','Check reasoning and handoff');submit.type='submit';form.append(fs,submit);const feedback=el('section');feedback.id='feedback';feedback.setAttribute('aria-live','polite');form.onsubmit=e=>{e.preventDefault();const checked=form.querySelector('input:checked');if(!checked)return;answers[c.id]=Number(checked.value);showFeedback(feedback,c);progress();};root.append(form,feedback);if(answers[c.id]!==undefined)showFeedback(feedback,c);progress();}
function showFeedback(root,c){root.replaceChildren(el('h3',answers[c.id]===c.correct?'Matches the reasoning in this case':'Separate verified facts from unverified promises'),el('p','Suggested action in this case: '+c.options[c.correct]),el('p',c.why),el('h3','Example handoff to the owner'),el('p',c.handoff,'handoff'));const refs=el('p','Policy references: '+c.rules.map(r=>r.id).join(', '),'small');root.append(refs);}
function exportText(){if(!Object.keys(answers).length){byId('notice').textContent='Review one case first.';return;}const lines=['Support Decision Practice / Fictional case review','This does not determine real customer treatment, professional qualifications or refund rights.',''];TRAINING_CASES.forEach(c=>{lines.push(c.id+' '+c.title,answers[c.id]===undefined?'Not answered':'Chosen action: '+c.options[answers[c.id]],'Fictional policy: '+c.rules.map(r=>r.id+' '+r.text).join(' / '),'Handoff example: '+c.handoff,'');});const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=el('a');a.href=url;a.download='reply-training-review.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);byId('notice').textContent='Review file created. Check your downloads.';}
byId('export').onclick=exportText;byId('reset').onclick=()=>{answers={};active=0;render();byId('notice').textContent='Progress reset. Previously saved files are unchanged.';};render();
